### ISSUE TITLE
factor to character in pdf_fonts

### ISSUE THREAD

**Issue by sckott** [jeroenooms/pdftools#1]
Minor point, but I get 

```r
str(pdf_fonts("R-exts.pdf"))
#> 'data.frame':	22 obs. of  4 variables:
#>  $ name    : Factor w/ 22 levels "AYLODX+CMTI10",..: 17 12 9 5 16 21 19 1 6 3 ...
#>  $ type    : Factor w/ 1 level "type1": 1 1 1 1 1 1 1 1 1 1 ...
#>  $ embedded: logi  TRUE TRUE TRUE TRUE TRUE TRUE ...
#>  $ file    : Factor w/ 1 level "": 1 1 1 1 1 1 1 1 1 1 ...
```

would you be willing to change the factor columns to character? seems safer, less likely to cause problems downstream if users don't realize they're dealing with factors

**Comment by jeroenooms** [comment]
Good catch, that is definitely not intended.

**Comment by jeroenooms** [comment]
Fixed @ https://github.com/jeroenooms/pdftools/commit/e91e4c92a1d3ae1bf750a7136cc22de39cc58fe3.
